### ISSUE TITLE
Multiplayer (movement for now)

### ISSUE THREAD

**Issue by EdgarTip** [MigDinny/EngageX#12]
Implement multiplayer in game. This issue is considered finished when 2 different players appear in the same map.

- [x] tick system on a thread
- [x] broadcast game state every tick
- [x] handle inputs (movement for now) on server 
- [x] client reads player list and renders all players keeping their positions updated
- [x] client is able to start the lobby
- [x] client receives server messages and is able to interpret them in a correct and structured way
- [x] **finally:** two or more players can move around !

**Comment by MigDinny** [comment]
Everything is done now on [multiplayer-edgar](https://github.com/MigDinny/EngageX/tree/multiplayer-edgar) branch.

Some minor bugs are there but nothing that compromises the multiplayer feature itself

- map is not aligned, players are disaligned, probably a thing with an array starting in 0 or 1

- animations are off

**Comment by MigDinny** [comment]
@EdgarTip faz PR e deixa a tua review, para eu depois dar final review and merge
