### ISSUE TITLE
Check LAN communications 

### ISSUE THREAD

**Issue by EdgarTip** [MigDinny/EngageX#14]
- [ ] Check if server can be used in LAN

**Comment by MigDinny** [comment]
![image](https://user-images.githubusercontent.com/6632800/204296963-c2637b34-337d-4c8f-bcf0-3f3fe64a16d5.png)

**Comment by MigDinny** [comment]
made a commit e6bfa1aefdea2a299aca597b7a2c3c28911ea91c

this fixes the network lan issue. the server was listening to the loopback interface and not to the LAN interface. client connects to 192.168.1.122 (hardcoded) -- ofc this needs to be addressed in the future
