### ISSUE TITLE
UI tune and fixes

### ISSUE THREAD

**Issue by MigDinny** [MigDinny/EngageX#29]
- [ ] let's decide a font family for the game once and for all
- [ ] let's redesign the skill buttons, maybe change the font and the background-color, maybe texturize it a bit
- [ ] select the perfect and well-thinked textures for the game,. we need to think on why we selected such textures and not just because they were the first we found out. balance the colors. we do not need neither too much green neither too much contrast, etc...
- [x] change the texture for the HUD background, maybe have a touch on those UI components, their borders, shadows etc. maybe get a texturized frame for the whole game?? 
- [x] redesign home menu
- [x] endgame

Feel free to add more goals to this issue. The main goal is to achieve a well-designed artifact with well chosen colors, sizes, positions, textures...

I request everyone's help on this one. You can pick a single task and create a branch for it.

**Comment by EdgarTip** [comment]
The project was discontinued. I will close this issue.
